services:
  # 1. PostgreSQL - Data Warehouse
  postgres-dw:
    image: postgres:15
    env_file: .env
    ports:
      - "5434:5432" 
    volumes:
      - postgres_dw_data:/var/lib/postgresql/data

  # 2. MongoDB - A Origem dos Dados
  mongo:
    image: mongo:6.0
    env_file: .env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 3. Metabase - Data Visualization
  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"

volumes:
  postgres_dw_data:
  mongo_data: